# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from cloud.v1 import cloud_pb2 as cloud_dot_v1_dot_cloud__pb2


class CloudServiceStub(object):
    """Field reservation policy: see common/v1/common.proto.
    When removing fields, always add `reserved` for both the number and name.

    CloudService handles cloud credential vending for AWS, GCP, and other providers.
    Separated from EnforcementService (which owns CanAccess) to keep credential
    vending as a standalone concern. Implemented by cloud provider plugins (e.g., cloud-aws).
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetCredentials = channel.unary_unary(
                '/ratatouille.cloud.v1.CloudService/GetCredentials',
                request_serializer=cloud_dot_v1_dot_cloud__pb2.GetCredentialsRequest.SerializeToString,
                response_deserializer=cloud_dot_v1_dot_cloud__pb2.GetCredentialsResponse.FromString,
                _registered_method=True)


class CloudServiceServicer(object):
    """Field reservation policy: see common/v1/common.proto.
    When removing fields, always add `reserved` for both the number and name.

    CloudService handles cloud credential vending for AWS, GCP, and other providers.
    Separated from EnforcementService (which owns CanAccess) to keep credential
    vending as a standalone concern. Implemented by cloud provider plugins (e.g., cloud-aws).
    """

    def GetCredentials(self, request, context):
        """Vend scoped S3 credentials for a user within a namespace.
        Returns temporary credentials (e.g., AWS STS AssumeRole) scoped to the
        namespace's S3 prefix.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CloudServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetCredentials': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCredentials,
                    request_deserializer=cloud_dot_v1_dot_cloud__pb2.GetCredentialsRequest.FromString,
                    response_serializer=cloud_dot_v1_dot_cloud__pb2.GetCredentialsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ratatouille.cloud.v1.CloudService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ratatouille.cloud.v1.CloudService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CloudService(object):
    """Field reservation policy: see common/v1/common.proto.
    When removing fields, always add `reserved` for both the number and name.

    CloudService handles cloud credential vending for AWS, GCP, and other providers.
    Separated from EnforcementService (which owns CanAccess) to keep credential
    vending as a standalone concern. Implemented by cloud provider plugins (e.g., cloud-aws).
    """

    @staticmethod
    def GetCredentials(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ratatouille.cloud.v1.CloudService/GetCredentials',
            cloud_dot_v1_dot_cloud__pb2.GetCredentialsRequest.SerializeToString,
            cloud_dot_v1_dot_cloud__pb2.GetCredentialsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
