# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from query.v1 import query_pb2 as query_dot_v1_dot_query__pb2


class QueryServiceStub(object):
    """Field reservation policy: see common/v1/common.proto.
    When removing fields, always add `reserved` for both the number and name.

    QueryService handles interactive DuckDB queries.
    Implemented by ratq (Python query sidecar).
    Called by ratd (Go platform).
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ExecuteQuery = channel.unary_unary(
                '/ratatouille.query.v1.QueryService/ExecuteQuery',
                request_serializer=query_dot_v1_dot_query__pb2.ExecuteQueryRequest.SerializeToString,
                response_deserializer=query_dot_v1_dot_query__pb2.ExecuteQueryResponse.FromString,
                _registered_method=True)
        self.GetSchema = channel.unary_unary(
                '/ratatouille.query.v1.QueryService/GetSchema',
                request_serializer=query_dot_v1_dot_query__pb2.GetSchemaRequest.SerializeToString,
                response_deserializer=query_dot_v1_dot_query__pb2.GetSchemaResponse.FromString,
                _registered_method=True)
        self.PreviewTable = channel.unary_unary(
                '/ratatouille.query.v1.QueryService/PreviewTable',
                request_serializer=query_dot_v1_dot_query__pb2.PreviewTableRequest.SerializeToString,
                response_deserializer=query_dot_v1_dot_query__pb2.PreviewTableResponse.FromString,
                _registered_method=True)
        self.ListTables = channel.unary_unary(
                '/ratatouille.query.v1.QueryService/ListTables',
                request_serializer=query_dot_v1_dot_query__pb2.ListTablesRequest.SerializeToString,
                response_deserializer=query_dot_v1_dot_query__pb2.ListTablesResponse.FromString,
                _registered_method=True)


class QueryServiceServicer(object):
    """Field reservation policy: see common/v1/common.proto.
    When removing fields, always add `reserved` for both the number and name.

    QueryService handles interactive DuckDB queries.
    Implemented by ratq (Python query sidecar).
    Called by ratd (Go platform).
    """

    def ExecuteQuery(self, request, context):
        """Execute a SQL query and return results.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSchema(self, request, context):
        """Get schema for a table.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PreviewTable(self, request, context):
        """Preview first N rows of a table.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListTables(self, request, context):
        """List all tables accessible in a namespace.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_QueryServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ExecuteQuery': grpc.unary_unary_rpc_method_handler(
                    servicer.ExecuteQuery,
                    request_deserializer=query_dot_v1_dot_query__pb2.ExecuteQueryRequest.FromString,
                    response_serializer=query_dot_v1_dot_query__pb2.ExecuteQueryResponse.SerializeToString,
            ),
            'GetSchema': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSchema,
                    request_deserializer=query_dot_v1_dot_query__pb2.GetSchemaRequest.FromString,
                    response_serializer=query_dot_v1_dot_query__pb2.GetSchemaResponse.SerializeToString,
            ),
            'PreviewTable': grpc.unary_unary_rpc_method_handler(
                    servicer.PreviewTable,
                    request_deserializer=query_dot_v1_dot_query__pb2.PreviewTableRequest.FromString,
                    response_serializer=query_dot_v1_dot_query__pb2.PreviewTableResponse.SerializeToString,
            ),
            'ListTables': grpc.unary_unary_rpc_method_handler(
                    servicer.ListTables,
                    request_deserializer=query_dot_v1_dot_query__pb2.ListTablesRequest.FromString,
                    response_serializer=query_dot_v1_dot_query__pb2.ListTablesResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ratatouille.query.v1.QueryService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ratatouille.query.v1.QueryService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class QueryService(object):
    """Field reservation policy: see common/v1/common.proto.
    When removing fields, always add `reserved` for both the number and name.

    QueryService handles interactive DuckDB queries.
    Implemented by ratq (Python query sidecar).
    Called by ratd (Go platform).
    """

    @staticmethod
    def ExecuteQuery(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ratatouille.query.v1.QueryService/ExecuteQuery',
            query_dot_v1_dot_query__pb2.ExecuteQueryRequest.SerializeToString,
            query_dot_v1_dot_query__pb2.ExecuteQueryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSchema(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ratatouille.query.v1.QueryService/GetSchema',
            query_dot_v1_dot_query__pb2.GetSchemaRequest.SerializeToString,
            query_dot_v1_dot_query__pb2.GetSchemaResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PreviewTable(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ratatouille.query.v1.QueryService/PreviewTable',
            query_dot_v1_dot_query__pb2.PreviewTableRequest.SerializeToString,
            query_dot_v1_dot_query__pb2.PreviewTableResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListTables(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ratatouille.query.v1.QueryService/ListTables',
            query_dot_v1_dot_query__pb2.ListTablesRequest.SerializeToString,
            query_dot_v1_dot_query__pb2.ListTablesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
