# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from sharing.v1 import sharing_pb2 as sharing_dot_v1_dot_sharing__pb2


class SharingServiceStub(object):
    """Field reservation policy: see common/v1/common.proto.
    When removing fields, always add `reserved` for both the number and name.

    SharingService manages resource access grants between users.
    Implemented by the sharing plugin container.
    Called by ratd when users share pipelines, namespaces, or other resources.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ShareResource = channel.unary_unary(
                '/ratatouille.sharing.v1.SharingService/ShareResource',
                request_serializer=sharing_dot_v1_dot_sharing__pb2.ShareResourceRequest.SerializeToString,
                response_deserializer=sharing_dot_v1_dot_sharing__pb2.ShareResourceResponse.FromString,
                _registered_method=True)
        self.RevokeAccess = channel.unary_unary(
                '/ratatouille.sharing.v1.SharingService/RevokeAccess',
                request_serializer=sharing_dot_v1_dot_sharing__pb2.RevokeAccessRequest.SerializeToString,
                response_deserializer=sharing_dot_v1_dot_sharing__pb2.RevokeAccessResponse.FromString,
                _registered_method=True)
        self.ListAccess = channel.unary_unary(
                '/ratatouille.sharing.v1.SharingService/ListAccess',
                request_serializer=sharing_dot_v1_dot_sharing__pb2.ListAccessRequest.SerializeToString,
                response_deserializer=sharing_dot_v1_dot_sharing__pb2.ListAccessResponse.FromString,
                _registered_method=True)
        self.TransferOwnership = channel.unary_unary(
                '/ratatouille.sharing.v1.SharingService/TransferOwnership',
                request_serializer=sharing_dot_v1_dot_sharing__pb2.TransferOwnershipRequest.SerializeToString,
                response_deserializer=sharing_dot_v1_dot_sharing__pb2.TransferOwnershipResponse.FromString,
                _registered_method=True)


class SharingServiceServicer(object):
    """Field reservation policy: see common/v1/common.proto.
    When removing fields, always add `reserved` for both the number and name.

    SharingService manages resource access grants between users.
    Implemented by the sharing plugin container.
    Called by ratd when users share pipelines, namespaces, or other resources.
    """

    def ShareResource(self, request, context):
        """Grant access to a resource.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RevokeAccess(self, request, context):
        """Revoke a previously granted access.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListAccess(self, request, context):
        """List all access grants for a resource.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TransferOwnership(self, request, context):
        """Transfer ownership of a resource to another user.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SharingServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ShareResource': grpc.unary_unary_rpc_method_handler(
                    servicer.ShareResource,
                    request_deserializer=sharing_dot_v1_dot_sharing__pb2.ShareResourceRequest.FromString,
                    response_serializer=sharing_dot_v1_dot_sharing__pb2.ShareResourceResponse.SerializeToString,
            ),
            'RevokeAccess': grpc.unary_unary_rpc_method_handler(
                    servicer.RevokeAccess,
                    request_deserializer=sharing_dot_v1_dot_sharing__pb2.RevokeAccessRequest.FromString,
                    response_serializer=sharing_dot_v1_dot_sharing__pb2.RevokeAccessResponse.SerializeToString,
            ),
            'ListAccess': grpc.unary_unary_rpc_method_handler(
                    servicer.ListAccess,
                    request_deserializer=sharing_dot_v1_dot_sharing__pb2.ListAccessRequest.FromString,
                    response_serializer=sharing_dot_v1_dot_sharing__pb2.ListAccessResponse.SerializeToString,
            ),
            'TransferOwnership': grpc.unary_unary_rpc_method_handler(
                    servicer.TransferOwnership,
                    request_deserializer=sharing_dot_v1_dot_sharing__pb2.TransferOwnershipRequest.FromString,
                    response_serializer=sharing_dot_v1_dot_sharing__pb2.TransferOwnershipResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ratatouille.sharing.v1.SharingService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ratatouille.sharing.v1.SharingService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SharingService(object):
    """Field reservation policy: see common/v1/common.proto.
    When removing fields, always add `reserved` for both the number and name.

    SharingService manages resource access grants between users.
    Implemented by the sharing plugin container.
    Called by ratd when users share pipelines, namespaces, or other resources.
    """

    @staticmethod
    def ShareResource(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ratatouille.sharing.v1.SharingService/ShareResource',
            sharing_dot_v1_dot_sharing__pb2.ShareResourceRequest.SerializeToString,
            sharing_dot_v1_dot_sharing__pb2.ShareResourceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RevokeAccess(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ratatouille.sharing.v1.SharingService/RevokeAccess',
            sharing_dot_v1_dot_sharing__pb2.RevokeAccessRequest.SerializeToString,
            sharing_dot_v1_dot_sharing__pb2.RevokeAccessResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListAccess(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ratatouille.sharing.v1.SharingService/ListAccess',
            sharing_dot_v1_dot_sharing__pb2.ListAccessRequest.SerializeToString,
            sharing_dot_v1_dot_sharing__pb2.ListAccessResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TransferOwnership(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ratatouille.sharing.v1.SharingService/TransferOwnership',
            sharing_dot_v1_dot_sharing__pb2.TransferOwnershipRequest.SerializeToString,
            sharing_dot_v1_dot_sharing__pb2.TransferOwnershipResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
