# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from common.v1 import common_pb2 as common_dot_v1_dot_common__pb2
from runner.v1 import runner_pb2 as runner_dot_v1_dot_runner__pb2


class RunnerServiceStub(object):
    """Field reservation policy: see common/v1/common.proto.
    When removing fields, always add `reserved` for both the number and name.

    RunnerService handles pipeline execution.
    Implemented by the Python runner container.
    Called by ratd (Go platform).
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SubmitPipeline = channel.unary_unary(
                '/ratatouille.runner.v1.RunnerService/SubmitPipeline',
                request_serializer=runner_dot_v1_dot_runner__pb2.SubmitPipelineRequest.SerializeToString,
                response_deserializer=runner_dot_v1_dot_runner__pb2.SubmitPipelineResponse.FromString,
                _registered_method=True)
        self.GetRunStatus = channel.unary_unary(
                '/ratatouille.runner.v1.RunnerService/GetRunStatus',
                request_serializer=common_dot_v1_dot_common__pb2.GetRunStatusRequest.SerializeToString,
                response_deserializer=common_dot_v1_dot_common__pb2.GetRunStatusResponse.FromString,
                _registered_method=True)
        self.StreamLogs = channel.unary_stream(
                '/ratatouille.runner.v1.RunnerService/StreamLogs',
                request_serializer=common_dot_v1_dot_common__pb2.StreamLogsRequest.SerializeToString,
                response_deserializer=common_dot_v1_dot_common__pb2.LogEntry.FromString,
                _registered_method=True)
        self.CancelRun = channel.unary_unary(
                '/ratatouille.runner.v1.RunnerService/CancelRun',
                request_serializer=common_dot_v1_dot_common__pb2.CancelRunRequest.SerializeToString,
                response_deserializer=common_dot_v1_dot_common__pb2.CancelRunResponse.FromString,
                _registered_method=True)
        self.PreviewPipeline = channel.unary_unary(
                '/ratatouille.runner.v1.RunnerService/PreviewPipeline',
                request_serializer=runner_dot_v1_dot_runner__pb2.PreviewPipelineRequest.SerializeToString,
                response_deserializer=runner_dot_v1_dot_runner__pb2.PreviewPipelineResponse.FromString,
                _registered_method=True)
        self.ValidatePipeline = channel.unary_unary(
                '/ratatouille.runner.v1.RunnerService/ValidatePipeline',
                request_serializer=runner_dot_v1_dot_runner__pb2.ValidatePipelineRequest.SerializeToString,
                response_deserializer=runner_dot_v1_dot_runner__pb2.ValidatePipelineResponse.FromString,
                _registered_method=True)
        self.ListPlugins = channel.unary_unary(
                '/ratatouille.runner.v1.RunnerService/ListPlugins',
                request_serializer=runner_dot_v1_dot_runner__pb2.ListPluginsRequest.SerializeToString,
                response_deserializer=runner_dot_v1_dot_runner__pb2.ListPluginsResponse.FromString,
                _registered_method=True)


class RunnerServiceServicer(object):
    """Field reservation policy: see common/v1/common.proto.
    When removing fields, always add `reserved` for both the number and name.

    RunnerService handles pipeline execution.
    Implemented by the Python runner container.
    Called by ratd (Go platform).
    """

    def SubmitPipeline(self, request, context):
        """Submit a pipeline for execution.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRunStatus(self, request, context):
        """Get the current status of a run.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamLogs(self, request, context):
        """Stream logs from a running or completed pipeline.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CancelRun(self, request, context):
        """Cancel a running pipeline.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PreviewPipeline(self, request, context):
        """Preview a pipeline without writing to the data lake.
        Executes the transformation with LIMIT, returns sample results + profiling stats.
        Ephemeral — no DB row in runs, no Iceberg write, no Nessie branch.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ValidatePipeline(self, request, context):
        """Validate pipeline templates (Jinja syntax, anti-patterns) without executing.
        Called by the platform before publishing to catch errors early.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListPlugins(self, request, context):
        """List all discovered runner plugins (entry points installed in the runner container).
        Called by the platform to expose runner plugin metadata to the portal UI.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RunnerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SubmitPipeline': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitPipeline,
                    request_deserializer=runner_dot_v1_dot_runner__pb2.SubmitPipelineRequest.FromString,
                    response_serializer=runner_dot_v1_dot_runner__pb2.SubmitPipelineResponse.SerializeToString,
            ),
            'GetRunStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRunStatus,
                    request_deserializer=common_dot_v1_dot_common__pb2.GetRunStatusRequest.FromString,
                    response_serializer=common_dot_v1_dot_common__pb2.GetRunStatusResponse.SerializeToString,
            ),
            'StreamLogs': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamLogs,
                    request_deserializer=common_dot_v1_dot_common__pb2.StreamLogsRequest.FromString,
                    response_serializer=common_dot_v1_dot_common__pb2.LogEntry.SerializeToString,
            ),
            'CancelRun': grpc.unary_unary_rpc_method_handler(
                    servicer.CancelRun,
                    request_deserializer=common_dot_v1_dot_common__pb2.CancelRunRequest.FromString,
                    response_serializer=common_dot_v1_dot_common__pb2.CancelRunResponse.SerializeToString,
            ),
            'PreviewPipeline': grpc.unary_unary_rpc_method_handler(
                    servicer.PreviewPipeline,
                    request_deserializer=runner_dot_v1_dot_runner__pb2.PreviewPipelineRequest.FromString,
                    response_serializer=runner_dot_v1_dot_runner__pb2.PreviewPipelineResponse.SerializeToString,
            ),
            'ValidatePipeline': grpc.unary_unary_rpc_method_handler(
                    servicer.ValidatePipeline,
                    request_deserializer=runner_dot_v1_dot_runner__pb2.ValidatePipelineRequest.FromString,
                    response_serializer=runner_dot_v1_dot_runner__pb2.ValidatePipelineResponse.SerializeToString,
            ),
            'ListPlugins': grpc.unary_unary_rpc_method_handler(
                    servicer.ListPlugins,
                    request_deserializer=runner_dot_v1_dot_runner__pb2.ListPluginsRequest.FromString,
                    response_serializer=runner_dot_v1_dot_runner__pb2.ListPluginsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ratatouille.runner.v1.RunnerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ratatouille.runner.v1.RunnerService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RunnerService(object):
    """Field reservation policy: see common/v1/common.proto.
    When removing fields, always add `reserved` for both the number and name.

    RunnerService handles pipeline execution.
    Implemented by the Python runner container.
    Called by ratd (Go platform).
    """

    @staticmethod
    def SubmitPipeline(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ratatouille.runner.v1.RunnerService/SubmitPipeline',
            runner_dot_v1_dot_runner__pb2.SubmitPipelineRequest.SerializeToString,
            runner_dot_v1_dot_runner__pb2.SubmitPipelineResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRunStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ratatouille.runner.v1.RunnerService/GetRunStatus',
            common_dot_v1_dot_common__pb2.GetRunStatusRequest.SerializeToString,
            common_dot_v1_dot_common__pb2.GetRunStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamLogs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/ratatouille.runner.v1.RunnerService/StreamLogs',
            common_dot_v1_dot_common__pb2.StreamLogsRequest.SerializeToString,
            common_dot_v1_dot_common__pb2.LogEntry.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CancelRun(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ratatouille.runner.v1.RunnerService/CancelRun',
            common_dot_v1_dot_common__pb2.CancelRunRequest.SerializeToString,
            common_dot_v1_dot_common__pb2.CancelRunResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PreviewPipeline(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ratatouille.runner.v1.RunnerService/PreviewPipeline',
            runner_dot_v1_dot_runner__pb2.PreviewPipelineRequest.SerializeToString,
            runner_dot_v1_dot_runner__pb2.PreviewPipelineResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ValidatePipeline(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ratatouille.runner.v1.RunnerService/ValidatePipeline',
            runner_dot_v1_dot_runner__pb2.ValidatePipelineRequest.SerializeToString,
            runner_dot_v1_dot_runner__pb2.ValidatePipelineResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListPlugins(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ratatouille.runner.v1.RunnerService/ListPlugins',
            runner_dot_v1_dot_runner__pb2.ListPluginsRequest.SerializeToString,
            runner_dot_v1_dot_runner__pb2.ListPluginsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
