# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from storage.v1 import storage_pb2 as storage_dot_v1_dot_storage__pb2


class StorageServiceStub(object):
    """Field reservation policy: see common/v1/common.proto.
    When removing fields, always add `reserved` for both the number and name.

    StorageService is the pluggable object-storage axis. It vends storage
    descriptors the engine uses for native I/O, and performs the few control-plane
    object operations the orchestrator needs (list, move -- e.g. landing-zone
    archival). It never touches table format or semantics, only bytes.
    Implemented by storage plugins (e.g. rat-storage-s3). Called by the runner.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Describe = channel.unary_unary(
                '/ratatouille.storage.v1.StorageService/Describe',
                request_serializer=storage_dot_v1_dot_storage__pb2.DescribeRequest.SerializeToString,
                response_deserializer=storage_dot_v1_dot_storage__pb2.DescribeResponse.FromString,
                _registered_method=True)
        self.VendDescriptor = channel.unary_unary(
                '/ratatouille.storage.v1.StorageService/VendDescriptor',
                request_serializer=storage_dot_v1_dot_storage__pb2.VendDescriptorRequest.SerializeToString,
                response_deserializer=storage_dot_v1_dot_storage__pb2.VendDescriptorResponse.FromString,
                _registered_method=True)
        self.ListObjects = channel.unary_unary(
                '/ratatouille.storage.v1.StorageService/ListObjects',
                request_serializer=storage_dot_v1_dot_storage__pb2.ListObjectsRequest.SerializeToString,
                response_deserializer=storage_dot_v1_dot_storage__pb2.ListObjectsResponse.FromString,
                _registered_method=True)
        self.MoveObjects = channel.unary_unary(
                '/ratatouille.storage.v1.StorageService/MoveObjects',
                request_serializer=storage_dot_v1_dot_storage__pb2.MoveObjectsRequest.SerializeToString,
                response_deserializer=storage_dot_v1_dot_storage__pb2.MoveObjectsResponse.FromString,
                _registered_method=True)


class StorageServiceServicer(object):
    """Field reservation policy: see common/v1/common.proto.
    When removing fields, always add `reserved` for both the number and name.

    StorageService is the pluggable object-storage axis. It vends storage
    descriptors the engine uses for native I/O, and performs the few control-plane
    object operations the orchestrator needs (list, move -- e.g. landing-zone
    archival). It never touches table format or semantics, only bytes.
    Implemented by storage plugins (e.g. rat-storage-s3). Called by the runner.
    """

    def Describe(self, request, context):
        """Report identity + which storage schemes this plugin serves.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def VendDescriptor(self, request, context):
        """Vend a ready-to-use StorageDescriptor for a location (handed to an engine).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListObjects(self, request, context):
        """List object keys under a prefix (control-plane housekeeping).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MoveObjects(self, request, context):
        """Move/archive object keys to a destination prefix (e.g. processed landing zones).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_StorageServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Describe': grpc.unary_unary_rpc_method_handler(
                    servicer.Describe,
                    request_deserializer=storage_dot_v1_dot_storage__pb2.DescribeRequest.FromString,
                    response_serializer=storage_dot_v1_dot_storage__pb2.DescribeResponse.SerializeToString,
            ),
            'VendDescriptor': grpc.unary_unary_rpc_method_handler(
                    servicer.VendDescriptor,
                    request_deserializer=storage_dot_v1_dot_storage__pb2.VendDescriptorRequest.FromString,
                    response_serializer=storage_dot_v1_dot_storage__pb2.VendDescriptorResponse.SerializeToString,
            ),
            'ListObjects': grpc.unary_unary_rpc_method_handler(
                    servicer.ListObjects,
                    request_deserializer=storage_dot_v1_dot_storage__pb2.ListObjectsRequest.FromString,
                    response_serializer=storage_dot_v1_dot_storage__pb2.ListObjectsResponse.SerializeToString,
            ),
            'MoveObjects': grpc.unary_unary_rpc_method_handler(
                    servicer.MoveObjects,
                    request_deserializer=storage_dot_v1_dot_storage__pb2.MoveObjectsRequest.FromString,
                    response_serializer=storage_dot_v1_dot_storage__pb2.MoveObjectsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ratatouille.storage.v1.StorageService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ratatouille.storage.v1.StorageService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class StorageService(object):
    """Field reservation policy: see common/v1/common.proto.
    When removing fields, always add `reserved` for both the number and name.

    StorageService is the pluggable object-storage axis. It vends storage
    descriptors the engine uses for native I/O, and performs the few control-plane
    object operations the orchestrator needs (list, move -- e.g. landing-zone
    archival). It never touches table format or semantics, only bytes.
    Implemented by storage plugins (e.g. rat-storage-s3). Called by the runner.
    """

    @staticmethod
    def Describe(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ratatouille.storage.v1.StorageService/Describe',
            storage_dot_v1_dot_storage__pb2.DescribeRequest.SerializeToString,
            storage_dot_v1_dot_storage__pb2.DescribeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def VendDescriptor(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ratatouille.storage.v1.StorageService/VendDescriptor',
            storage_dot_v1_dot_storage__pb2.VendDescriptorRequest.SerializeToString,
            storage_dot_v1_dot_storage__pb2.VendDescriptorResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListObjects(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ratatouille.storage.v1.StorageService/ListObjects',
            storage_dot_v1_dot_storage__pb2.ListObjectsRequest.SerializeToString,
            storage_dot_v1_dot_storage__pb2.ListObjectsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def MoveObjects(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ratatouille.storage.v1.StorageService/MoveObjects',
            storage_dot_v1_dot_storage__pb2.MoveObjectsRequest.SerializeToString,
            storage_dot_v1_dot_storage__pb2.MoveObjectsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
