#!/usr/bin/env python3
"""Combine per-component license data into root THIRD-PARTY-NOTICES.md and website JSON.

Reads intermediate files from licenses/ (*.csv for Go, *.json for Python/Node)
and produces:
  - THIRD-PARTY-NOTICES.md at the repo root (combined, with component sections)
  - website/data/licenses.json (structured data for the acknowledgments page)
"""

import argparse
import csv
import json
import os
from datetime import datetime, timezone
from io import StringIO
from pathlib import Path

COMPONENTS = [
    {"key": "platform", "label": "platform (ratd)", "lang": "go"},
    {"key": "runner", "label": "runner", "lang": "python"},
    {"key": "query", "label": "query", "lang": "python"},
    {"key": "portal", "label": "portal", "lang": "node"},
    {"key": "sdk-typescript", "label": "sdk-typescript", "lang": "node"},
    {"key": "website", "label": "website", "lang": "node"},
]


def parse_go_csv(csv_path: str, scope: str) -> list[dict]:
    """Parse a go-licenses CSV file (module,url,license) into structured entries."""
    entries = []
    if not os.path.isfile(csv_path):
        return entries
    with open(csv_path) as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            parts = line.split(",", 2)
            if len(parts) < 3:
                continue
            mod, url, license_type = parts
            entries.append({
                "name": mod.strip(),
                "version": "",
                "license": license_type.strip(),
                "url": url.strip() if url.strip() else "",
                "scope": scope,
            })
    return entries


def load_json_licenses(json_path: str) -> dict:
    """Load a JSON license file with runtime/dev split."""
    if not os.path.isfile(json_path):
        return {"runtime": [], "dev": []}
    with open(json_path) as f:
        return json.load(f)


def build_website_json(output_dir: str) -> list[dict]:
    """Build the combined JSON structure for the website."""
    all_deps = []

    for comp in COMPONENTS:
        key = comp["key"]
        label = comp["label"]

        if comp["lang"] == "go":
            runtime = parse_go_csv(os.path.join(output_dir, f"{key}-runtime.csv"), "runtime")
            dev = parse_go_csv(os.path.join(output_dir, f"{key}-dev.csv"), "dev")
            for entry in runtime:
                entry["component"] = label
            for entry in dev:
                entry["component"] = label
            all_deps.extend(runtime)
            all_deps.extend(dev)
        else:
            data = load_json_licenses(os.path.join(output_dir, f"{key}.json"))
            for entry in data.get("runtime", []):
                entry["component"] = label
                entry["scope"] = "runtime"
                all_deps.append(entry)
            for entry in data.get("dev", []):
                entry["component"] = label
                entry["scope"] = "dev"
                all_deps.append(entry)

    return all_deps


def build_root_notice(repo_root: str, output_dir: str) -> str:
    """Build the combined THIRD-PARTY-NOTICES.md content."""
    today = datetime.now(timezone.utc).strftime("%Y-%m-%d")

    lines = [
        "# Third-Party Licenses",
        "",
        "> Auto-generated by CI — do not edit manually.",
        f"> Last updated: {today}",
        "",
        "RAT is licensed under [Apache-2.0](LICENSE). This file lists all",
        "third-party dependencies and their respective licenses.",
        "",
        "## Components",
        "",
    ]

    for comp in COMPONENTS:
        key = comp["key"]
        label = comp["label"]
        lines.append(f"- [{label}]({key}/THIRD-PARTY-NOTICES.md)")

    lines.append("")

    # Inline all component sections
    for comp in COMPONENTS:
        key = comp["key"]
        md_path = os.path.join(output_dir, f"{key}.md")
        if os.path.isfile(md_path):
            lines.append("---")
            lines.append("")
            with open(md_path) as f:
                lines.append(f.read().strip())
            lines.append("")

    return "\n".join(lines) + "\n"


def main():
    parser = argparse.ArgumentParser(description="Combine license reports")
    parser.add_argument("--output-dir", required=True, help="Directory with intermediate license files")
    parser.add_argument("--repo-root", required=True, help="Repository root directory")
    args = parser.parse_args()

    output_dir = args.output_dir
    repo_root = args.repo_root

    # Build and write root THIRD-PARTY-NOTICES.md
    root_notice = build_root_notice(repo_root, output_dir)
    notice_path = os.path.join(repo_root, "THIRD-PARTY-NOTICES.md")
    with open(notice_path, "w") as f:
        f.write(root_notice)
    print(f"  Written: {notice_path}")

    # Build and write website JSON
    all_deps = build_website_json(output_dir)
    website_data_dir = os.path.join(repo_root, "website", "data")
    os.makedirs(website_data_dir, exist_ok=True)
    json_path = os.path.join(website_data_dir, "licenses.json")
    with open(json_path, "w") as f:
        json.dump(all_deps, f, indent=2)
    print(f"  Written: {json_path}")


if __name__ == "__main__":
    main()
